name: bus_attendance_app
description: App para controle de presença no ônibus estudantil

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 
  
  # Formatação de datas
  intl: ^0.19.0
  
  # Geração de PDF
  pdf: ^3.10.7
  printing: ^5.12.0
  
  # UI
  cupertino_icons: ^1.0.6

  # QR Code Scanner
  mobile_scanner: ^5.1.0

  # Geração de QR Code
  qr_flutter: ^4.1.0

  flutter_dotenv: ^5.1.0

  get: ^4.7.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/avatar/
    - assets/items/bg/

  # Fontes customizadas (opcional)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icone-app.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"