name: bus_attendance_app
description: App para controle de presença no ônibus estudantil

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase para backend
  supabase_flutter: ^2.3.4
  
  # Formatação de datas
  intl: ^0.19.0
  
  # Geração de PDF
  pdf: ^3.10.7
  printing: ^5.12.0
  
  # UI
  cupertino_icons: ^1.0.6

  # Geração de QR Code
  qr_flutter: ^4.1.0

  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:  
    - dotenv
  
  # Fontes customizadas (opcional)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
