// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_B-bKocE430icBeX4RKHordh9CwbpPg',
    appId: '1:281483438542:web:f9e229dbf1a8f119a3e39f',
    messagingSenderId: '281483438542',
    projectId: 'unibus-ad9a4',
    authDomain: 'unibus-ad9a4.firebaseapp.com',
    storageBucket: 'unibus-ad9a4.firebasestorage.app',
    measurementId: 'G-2RCFR9E0ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnO2QaO2aVtYtH5dvEq0UlkTJ_y0CwsUQ',
    appId: '1:281483438542:android:03efc3fa33fe7216a3e39f',
    messagingSenderId: '281483438542',
    projectId: 'unibus-ad9a4',
    storageBucket: 'unibus-ad9a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkFyccMtsBE3Jaw2Uw2YsiiQgyj2ljyPg',
    appId: '1:281483438542:ios:2140bfab5b9d5777a3e39f',
    messagingSenderId: '281483438542',
    projectId: 'unibus-ad9a4',
    storageBucket: 'unibus-ad9a4.firebasestorage.app',
    iosBundleId: 'com.example.unibus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkFyccMtsBE3Jaw2Uw2YsiiQgyj2ljyPg',
    appId: '1:281483438542:ios:2140bfab5b9d5777a3e39f',
    messagingSenderId: '281483438542',
    projectId: 'unibus-ad9a4',
    storageBucket: 'unibus-ad9a4.firebasestorage.app',
    iosBundleId: 'com.example.unibus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc_B-bKocE430icBeX4RKHordh9CwbpPg',
    appId: '1:281483438542:web:c084f69a4283282fa3e39f',
    messagingSenderId: '281483438542',
    projectId: 'unibus-ad9a4',
    authDomain: 'unibus-ad9a4.firebaseapp.com',
    storageBucket: 'unibus-ad9a4.firebasestorage.app',
    measurementId: 'G-XNBYXFQM5J',
  );
}
